export const questions = {
	A: [
		{
			question: '_____  name is George.',
			a: 'Me',
			b: 'I',
			c: 'My',
			correct: 'c',
		},
		{
			question: 'They _____  from Italy',
			a: 'is',
			b: 'are',
			c: 'do',
			correct: 'b',
		},
		{
			question: '_____  are you from?',
			a: 'What',
			b: 'Who',
			c: 'Where',
			correct: 'c',
		},
		{
			question: 'What do you do? I’m _____  student.',
			a: 'the',
			b: 'a',
			c: 'the',
			correct: 'b',
		},
		{
			question: 'Nurlan _____  at seven o’clock.',
			a: 'goes up',
			b: 'gets',
			c: 'gets up',
			correct: 'c',
		},
		{
			question: '_____  you like this computer game?',
			a: 'Are',
			b: 'Have',
			c: 'Do',
			correct: 'c',
		},
		{
			question: 'We _____ work in an office.',
			a: "don't",
			b: "hasn't",
			c: "doesn't",
			correct: 'a',
		},
		{
			question: 'Wednesday, Thursday, Friday, _____ ',
			a: 'Saturday',
			b: 'Tuesday',
			c: 'Monday',
			correct: 'a',
		},
		{
			question: '_____  he meet with friends?',
			a: 'Where',
			b: 'Does',
			c: 'Do',
			correct: 'b',
		},
		{
			question: 'Have you _____  a laptop?',
			a: 'any',
			b: 'have',
			c: 'got',
			correct: 'c',
		},
		{
			question: 'We don’t have _____ coffee.',
			a: 'a',
			b: 'any',
			c: 'got',
			correct: 'b',
		},
		{
			question: '_____  some money here.',
			a: "There're",
			b: 'There',
			c: "There's",
			correct: 'c',
		},
		{
			question: 'We _____  got a pet.',
			a: "haven't",
			b: "hasn't",
			c: "don't",
			correct: 'a',
		},
		{
			question: 'This car is very _____ .',
			a: 'expensive',
			b: 'rich',
			c: 'cost',
			correct: 'a',
		},
		{
			question: 'Have you got a printer? Yes, I _____ .',
			a: 'am',
			b: 'have',
			c: 'got',
			correct: 'b',
		},
		{
			question: 'It is a busy, _____  city.',
			a: 'traffic',
			b: 'quite',
			c: 'noisy',
			correct: 'c',
		},
		{
			question: 'They _____  at home last Friday.',
			a: 'was',
			b: 'are',
			c: 'were',
			correct: 'c',
		},
		{
			question: 'I _____  there for a long time.',
			a: 'lived',
			b: 'living',
			c: 'live',
			correct: 'a',
		},
		{
			question: 'He doesn’t _____  glasses.',
			a: 'put',
			b: 'wear',
			c: 'take',
			correct: 'b',
		},
		{
			question: 'The restaurant was _____  busy.',
			a: 'very',
			b: 'a lot',
			c: 'much',
			correct: 'a',
		},
		{
			question: 'Do you like the black _____ ?',
			a: 'it',
			b: 'that',
			c: 'one',
			correct: 'c',
		},
		{
			question: 'He _____  to France on holiday.',
			a: 'go',
			b: 'goed',
			c: 'went',
			correct: 'c',
		},
		{
			question: 'Yesterday was the _____  of April.',
			a: 'fifth',
			b: 'five',
			c: 'day five',
			correct: 'a',
		},
		{
			question: 'She’s got _____  hair.',
			a: 'blond, short',
			b: 'blond and short',
			c: 'short, blond',
			correct: 'c',
		},
		{
			question: 'I _____ watch films at the weekend.',
			a: 'usually',
			b: 'as usually',
			c: 'usual',
			correct: 'a',
		},
		{
			question: 'I _____  in an armchair at the moment.',
			a: 'sitting',
			b: "'m sitting",
			c: 'sit',
			correct: 'b',
		},
		{
			question: 'My sister is older _____  me.',
			a: 'then',
			b: 'that',
			c: 'than',
			correct: 'c',
		},
		{
			question: 'Their house is _____  biggest in the neighbourhood.',
			a: '-',
			b: 'a',
			c: 'the',
			correct: 'c',
		},
		{
			question: 'It’s the _____  difficult question in the test.',
			a: 'more',
			b: 'much',
			c: 'most',
			correct: 'c',
		},
		{
			question: 'The phone’s ringing:  _____  answer it.',
			a: "I'll",
			b: 'I',
			c: 'will',
			correct: 'a',
		},
		{
			question: 'Do you _____  classical or rock music?',
			a: 'rather',
			b: 'prefer',
			c: 'more',
			correct: 'b',
		},
		{
			question: 'He has _____  all the cake.',
			a: 'ate',
			b: 'eaten',
			c: 'eat',
			correct: 'b',
		},
		{
			question: 'The _____  have seen this cartoon before.',
			a: 'childs',
			b: 'child',
			c: 'children',
			correct: 'c',
		},
		{
			question: 'I’ve never met a celebrity _____ .',
			a: 'before',
			b: 'ago',
			c: 'early',
			correct: 'a',
		},
		{
			question: '_____  is the best exercise.',
			a: 'Swim',
			b: 'To swim',
			c: 'Swimming',
			correct: 'c',
		},
		{
			question: 'Have you _____  been on a winter sports holiday?',
			a: 'always',
			b: 'ever',
			c: 'sometimes',
			correct: 'b',
		},
		{
			question: 'I can’t _____  a foreign language.',
			a: 'speaking',
			b: 'speak',
			c: 'to speak',
			correct: 'b',
		},
		{
			question: 'They _____  pay for the tickets.',
			a: "havent't to",
			b: "don't have",
			c: "don't have to",
			correct: 'c',
		},
		{
			question: '_____  old is their son?',
			a: 'What',
			b: 'When',
			c: 'How',
			correct: 'c',
		},
		{
			question: 'Are you _____  for one or two weeks?',
			a: 'staying',
			b: 'stayed',
			c: 'stay',
			correct: 'a',
		},
		{
			question: 'Alex _____  to buy a new car.',
			a: 'will',
			b: 'going',
			c: 'is going',
			correct: 'c',
		},
		{
			question: 'I don’t _____  getting up early.',
			a: 'not like',
			b: 'want',
			c: 'enjoy',
			correct: 'c',
		},
		{
			question: 'We _____  like to visit your city.',
			a: 'would',
			b: 'will',
			c: 'are',
			correct: 'a',
		},
		{
			question: 'They _____  ever watch the news on TV.',
			a: 'hard',
			b: 'harder',
			c: 'hardly',
			correct: 'c',
		},
		{
			question: 'They won’t come, _____  they?',
			a: "won't",
			b: 'come',
			c: 'will',
			correct: 'c',
		},
		{
			question: 'He _____  know how to spell it.',
			a: "doesn't",
			b: "hasn't",
			c: "don't",
			correct: 'a',
		},
		{
			question: 'Carla _____  to music all morning.',
			a: 'listening',
			b: 'heard',
			c: 'listened',
			correct: 'c',
		},
		{
			question: 'They _____  come to the cinema with us.',
			a: "doesn't",
			b: 'not',
			c: "didn't",
			correct: 'c',
		},
		{
			question: 'I love detective stories. _____  do I.',
			a: 'Either',
			b: 'So',
			c: 'Neither',
			correct: 'b',
		},
		{
			question: 'We  _____ at the cafe at 7 pm.',
			a: 'meeting',
			b: "'re meet",
			c: "'re meeting",
			correct: 'c',
		},
	],
	B: [
		{
			question: '_____  name is George.',
			a: 'Me',
			b: 'I',
			c: 'My',
			correct: 'c',
		},
		{
			question: 'They _____  from Italy',
			a: 'is',
			b: 'are',
			c: 'do',
			correct: 'b',
		},
		{
			question: '_____  are you from?',
			a: 'What',
			b: 'Who',
			c: 'Where',
			correct: 'c',
		},
		{
			question: 'What do you do? I’m _____  student.',
			a: 'the',
			b: 'a',
			c: 'the',
			correct: 'b',
		},
		{
			question: 'Nurlan _____  at seven o’clock.',
			a: 'goes up',
			b: 'gets',
			c: 'gets up',
			correct: 'c',
		},
		{
			question: '_____  you like this computer game?',
			a: 'Are',
			b: 'Have',
			c: 'Do',
			correct: 'c',
		},
		{
			question: 'We _____ work in an office.',
			a: "don't",
			b: "hasn't",
			c: "doesn't",
			correct: 'a',
		},
		{
			question: 'Wednesday, Thursday, Friday, _____ ',
			a: 'Saturday',
			b: 'Tuesday',
			c: 'Monday',
			correct: 'a',
		},
		{
			question: '_____  he meet with friends?',
			a: 'Where',
			b: 'Does',
			c: 'Do',
			correct: 'b',
		},
		{
			question: 'Have you _____  a laptop?',
			a: 'any',
			b: 'have',
			c: 'got',
			correct: 'c',
		},
		{
			question: 'We don’t have _____ coffee.',
			a: 'a',
			b: 'any',
			c: 'got',
			correct: 'b',
		},
		{
			question: '_____  some money here.',
			a: "There're",
			b: 'There',
			c: "There's",
			correct: 'c',
		},
		{
			question: 'We _____  got a pet.',
			a: "haven't",
			b: "hasn't",
			c: "don't",
			correct: 'a',
		},
		{
			question: 'This car is very _____ .',
			a: 'expensive',
			b: 'rich',
			c: 'cost',
			correct: 'a',
		},
		{
			question: 'Have you got a printer? Yes, I _____ .',
			a: 'am',
			b: 'have',
			c: 'got',
			correct: 'b',
		},
		{
			question: 'It is a busy, _____  city.',
			a: 'traffic',
			b: 'quite',
			c: 'noisy',
			correct: 'c',
		},
		{
			question: 'They _____  at home last Friday.',
			a: 'was',
			b: 'are',
			c: 'were',
			correct: 'c',
		},
		{
			question: 'I _____  there for a long time.',
			a: 'lived',
			b: 'living',
			c: 'live',
			correct: 'a',
		},
		{
			question: 'He doesn’t _____  glasses.',
			a: 'put',
			b: 'wear',
			c: 'take',
			correct: 'b',
		},
		{
			question: 'The restaurant was _____  busy.',
			a: 'very',
			b: 'a lot',
			c: 'much',
			correct: 'a',
		},
		{
			question: 'Do you like the black _____ ?',
			a: 'it',
			b: 'that',
			c: 'one',
			correct: 'c',
		},
		{
			question: 'He _____  to France on holiday.',
			a: 'go',
			b: 'goed',
			c: 'went',
			correct: 'c',
		},
		{
			question: 'Yesterday was the _____  of April.',
			a: 'fifth',
			b: 'five',
			c: 'day five',
			correct: 'a',
		},
		{
			question: 'She’s got _____  hair.',
			a: 'blond, short',
			b: 'blond and short',
			c: 'short, blond',
			correct: 'c',
		},
		{
			question: 'I _____ watch films at the weekend.',
			a: 'usually',
			b: 'as usually',
			c: 'usual',
			correct: 'a',
		},
		{
			question: 'I _____  in an armchair at the moment.',
			a: 'sitting',
			b: "'m sitting",
			c: 'sit',
			correct: 'b',
		},
		{
			question: 'My sister is older _____  me.',
			a: 'then',
			b: 'that',
			c: 'than',
			correct: 'c',
		},
		{
			question: 'Their house is _____  biggest in the neighbourhood.',
			a: '-',
			b: 'a',
			c: 'the',
			correct: 'c',
		},
		{
			question: 'It’s the _____  difficult question in the test.',
			a: 'more',
			b: 'much',
			c: 'most',
			correct: 'c',
		},
		{
			question: 'The phone’s ringing:  _____  answer it.',
			a: "I'll",
			b: 'I',
			c: 'will',
			correct: 'a',
		},
		{
			question: 'Do you _____  classical or rock music?',
			a: 'rather',
			b: 'prefer',
			c: 'more',
			correct: 'b',
		},
		{
			question: 'He has _____  all the cake.',
			a: 'ate',
			b: 'eaten',
			c: 'eat',
			correct: 'b',
		},
		{
			question: 'The _____  have seen this cartoon before.',
			a: 'childs',
			b: 'child',
			c: 'children',
			correct: 'c',
		},
		{
			question: 'I’ve never met a celebrity _____ .',
			a: 'before',
			b: 'ago',
			c: 'early',
			correct: 'a',
		},
		{
			question: '_____  is the best exercise.',
			a: 'Swim',
			b: 'To swim',
			c: 'Swimming',
			correct: 'c',
		},
		{
			question: 'Have you _____  been on a winter sports holiday?',
			a: 'always',
			b: 'ever',
			c: 'sometimes',
			correct: 'b',
		},
		{
			question: 'I can’t _____  a foreign language.',
			a: 'speaking',
			b: 'speak',
			c: 'to speak',
			correct: 'b',
		},
		{
			question: 'They _____  pay for the tickets.',
			a: "havent't to",
			b: "don't have",
			c: "don't have to",
			correct: 'c',
		},
		{
			question: '_____  old is their son?',
			a: 'What',
			b: 'When',
			c: 'How',
			correct: 'c',
		},
		{
			question: 'Are you _____  for one or two weeks?',
			a: 'staying',
			b: 'stayed',
			c: 'stay',
			correct: 'a',
		},
		{
			question: 'Alex _____  to buy a new car.',
			a: 'will',
			b: 'going',
			c: 'is going',
			correct: 'c',
		},
		{
			question: 'I don’t _____  getting up early.',
			a: 'not like',
			b: 'want',
			c: 'enjoy',
			correct: 'c',
		},
		{
			question: 'We _____  like to visit your city.',
			a: 'would',
			b: 'will',
			c: 'are',
			correct: 'a',
		},
		{
			question: 'They _____  ever watch the news on TV.',
			a: 'hard',
			b: 'harder',
			c: 'hardly',
			correct: 'c',
		},
		{
			question: 'They won’t come, _____  they?',
			a: "won't",
			b: 'come',
			c: 'will',
			correct: 'c',
		},
		{
			question: 'He _____  know how to spell it.',
			a: "doesn't",
			b: "hasn't",
			c: "don't",
			correct: 'a',
		},
		{
			question: 'Carla _____  to music all morning.',
			a: 'listening',
			b: 'heard',
			c: 'listened',
			correct: 'c',
		},
		{
			question: 'They _____  come to the cinema with us.',
			a: "doesn't",
			b: 'not',
			c: "didn't",
			correct: 'c',
		},
		{
			question: 'I love detective stories. _____  do I.',
			a: 'Either',
			b: 'So',
			c: 'Neither',
			correct: 'b',
		},
		{
			question: 'We  _____ at the cafe at 7 pm.',
			a: 'meeting',
			b: "'re meet",
			c: "'re meeting",
			correct: 'c',
		},
		{
			question: 'They are going _____  in Lithuania next month.',
			a: 'to be',
			b: 'will be',
			c: 'be',
			d: 'being',
			correct: 'a',
		},
		{
			question: 'This is the university _____ I studied.',
			a: 'when',
			b: 'which',
			c: 'that',
			d: 'where',
			correct: 'd',
		},
		{
			question: 'Have you ever _____  in a jazz band?',
			a: 'seen',
			b: 'played',
			c: 'listened',
			d: 'wanted',
			correct: 'b',
		},
		{
			question: 'I’m _____  when I’m with my friends.',
			a: 'happyer',
			b: 'happier than',
			c: 'happier',
			d: 'the happy',
			correct: 'c',
		},
		{
			question: 'The result is _____  than I thought.',
			a: 'bad',
			b: 'badder',
			c: 'worse',
			d: 'worst',
			correct: 'c',
		},
		{
			question: 'Could you tell me the way _____ the police station ?',
			a: 'to',
			b: 'for',
			c: 'at',
			d: 'of',
			correct: 'a',
		},
		{
			question: 'Do you know what _____ ?',
			a: 'time is it',
			b: 'time is',
			c: 'time is now',
			d: 'time it is',
			correct: 'd',
		},
		{
			question: 'Were you _____  to arrive on time?',
			a: 'could',
			b: 'can',
			c: 'able',
			d: 'possible',
			correct: 'c',
		},
		{
			question: 'Everybody _____  wear a seat belt in the car.',
			a: 'must',
			b: 'must to',
			c: 'have to',
			d: 'have',
			correct: 'a',
		},
		{
			question: 'Tom has lived in this town _____  three years.',
			a: 'since',
			b: 'from',
			c: 'after',
			d: 'for',
			correct: 'd',
		},
		{
			question: 'We _____  work in that factory.',
			a: 'use to',
			b: 'were used to',
			c: 'used to',
			d: 'got used to',
			correct: 'c',
		},
		{
			question: 'I think it _____  be sunny tomorrow.',
			a: 'will probably',
			b: 'probably',
			c: 'is likely',
			d: 'will likely',
			correct: 'a',
		},
		{
			question: 'He _____  like his brother.',
			a: 'look',
			b: "isn't",
			c: "isn't look",
			d: 'is looking',
			correct: 'b',
		},
		{
			question: '_____  does your English teacher look like?',
			a: 'How',
			b: 'What',
			c: 'Why',
			d: 'Which',
			correct: 'b',
		},
		{
			question: 'I’ve got _____  many problems.',
			a: 'too',
			b: 'a',
			c: 'enough',
			d: 'over',
			correct: 'a',
		},
		{
			question: 'If we get up in time, _____ the train.',
			a: 'we have caught',
			b: 'we would catch',
			c: 'we had caought',
			d: "we'll catch",
			correct: 'd',
		},
		{
			question: 'They _____  to take a day off from work.',
			a: 'decide',
			b: 'deciding',
			c: 'decided',
			d: 'to decide',
			correct: 'c',
		},
		{
			question: 'I’m working _____  to save enough money for a new flat.',
			a: 'hardly',
			b: 'lots',
			c: 'hard',
			d: 'good',
			correct: 'c',
		},
		{
			question: 'I’m writing _____  to complain about the bad service.',
			a: 'for',
			b: 'in order',
			c: 'because',
			d: 'because of',
			correct: 'b',
		},
		{
			question: 'We understand that most problems _____ by teenagers.',
			a: 'cause',
			b: 'caused',
			c: 'were caused',
			d: 'were causing',
			correct: 'c',
		},
		{
			question: 'What _____  doing at the weekend?',
			a: 'have you like',
			b: 'are you liking',
			c: 'do you like',
			d: 'are you likely',
			correct: 'c',
		},
		{
			question: 'Football _____  in most countries.',
			a: 'plays',
			b: 'has played',
			c: 'is played',
			d: 'is playing',
			correct: 'c',
		},
		{
			question: 'Who was _____  the door?',
			a: 'at',
			b: 'on',
			c: 'in',
			d: 'of',
			correct: 'a',
		},
		{
			question: 'The children _____ breakfast when you called.',
			a: 'was having',
			b: 'had',
			c: 'were having',
			d: 'are having',
			correct: 'c',
		},
		{
			question: 'Your work is _____  better day by day.',
			a: 'being',
			b: 'doing',
			c: 'getting',
			d: 'falling',
			correct: 'c',
		},
		{
			question: 'I could play the piano _____  I could speak.',
			a: 'during',
			b: 'while',
			c: 'as well',
			d: 'before',
			correct: 'd',
		},
		{
			question: 'The flight was cancelled, so we _____  to the airport.',
			a: "didn't need to go",
			b: "weren't able to go",
			c: "hadn't to go",
			d: "mustn't go",
			correct: 'a',
		},
		{
			question: 'The problem was _____  solved',
			a: 'easy',
			b: 'easy to',
			c: 'an easy',
			d: 'easily',
			correct: 'd',
		},
		{
			question: 'It was a difficult journey, but I _____  get home.',
			a: 'should to',
			b: 'managed to',
			c: 'at last',
			d: 'was able',
			correct: 'b',
		},
		{
			question: 'We have  _____  heard the news.',
			a: 'already',
			b: 'always',
			c: 'yet',
			d: 'today',
			correct: 'c',
		},
		{
			question:
				'They arrived at the station, but the train _____  earlier.',
			a: 'has left',
			b: 'had leave',
			c: 'leaved',
			d: 'had left',
			correct: 'd',
		},
		{
			question: 'You can _____  walk or take a bus.',
			a: 'both',
			b: 'rather',
			c: 'either',
			d: 'neither',
			correct: 'c',
		},
		{
			question: 'If I _____  enough money, I’d  buy a house by the sea.',
			a: 'had',
			b: 'would have',
			c: 'have',
			d: 'will have',
			correct: 'a',
		},
		{
			question: 'The work  _____  correctly.',
			a: "hasn't done",
			b: "hasn't been done",
			c: "isn't been done",
			d: 'not been done',
			correct: 'b',
		},
		{
			question:
				'The accident wouldn’t have happened if you had been more _____ .',
			a: 'careful',
			b: 'carefully',
			c: 'careless',
			d: 'caring',
			correct: 'a',
		},
		{
			question: 'It _____  be possible some time in the future.',
			a: 'likely',
			b: 'hopefully',
			c: 'may',
			d: 'ought',
			correct: 'c',
		},
		{
			question: 'Schools then  _____ having more children in the class.',
			a: 'was used to',
			b: 'were used to',
			c: 'was use to',
			d: 'were use to',
			correct: 'b',
		},
		{
			question: 'We _____  to go to work at six in the morning.',
			a: "mustn't",
			b: "wouldn't",
			c: "didn't have",
			d: "needn't have",
			correct: 'c',
		},
		{
			question: 'Sally _____  an old photograph of the place.',
			a: 'came up',
			b: 'came across',
			c: 'came into',
			d: 'came after',
			correct: 'b',
		},
		{
			question: 'I _____  I had met her earlier.',
			a: 'hope',
			b: 'want',
			c: 'think',
			d: 'wish',
			correct: 'd',
		},
		{
			question:
				' We’ll have taken our exams _____  this time next month.',
			a: 'by',
			b: 'on',
			c: 'during',
			d: 'for',
			correct: 'a',
		},
		{
			question: 'I will fail my exams, _____ prepare well in advance.',
			a: "if I'm not",
			b: "if I wasn't",
			c: "if I haven't",
			d: "if I don't",
			correct: 'd',
		},
		{
			question: 'I  _____  wasted my time when I was at university.',
			a: 'regret',
			b: "shouldn't",
			c: 'ought not to',
			d: "shouldn't have",
			correct: 'd',
		},
		{
			question:
				'This is going to be my chance to _____  any difficulties.',
			a: 'repair',
			b: 'sort out',
			c: 'solve',
			d: 'improve',
			correct: 'b',
		},
		{
			question:
				'Working night shifts was difficult at first, but I soon _____  it.',
			a: 'got used to',
			b: 'get used to',
			c: 'changed to',
			d: 'used to',
			correct: 'a',
		},
		{
			question:
				'I wonder how you managed to cook _____  a delicious meal!',
			a: 'so',
			b: 'that',
			c: 'absolutely',
			d: 'such',
			correct: 'd',
		},
		{
			question:
				'The solution had been found _____  we hadn’t realised it.',
			a: 'however',
			b: 'despite',
			c: 'although',
			d: 'even',
			correct: 'c',
		},
		{
			question: 'Laura _____  what I had been doing for all that time.',
			a: 'asked to me',
			b: 'asked for me',
			c: 'asked of me',
			d: 'asked me',
			correct: 'd',
		},
		{
			question:
				'You _____  heard us coming because we were making a lot of noise.',
			a: 'must have',
			b: 'must',
			c: 'might',
			d: 'could',
			correct: 'a',
		},
		{
			question: 'Jerry _____  to give me a hand with the shopping.',
			a: 'suggested',
			b: 'offered',
			c: 'invited',
			d: 'told',
			correct: 'b',
		},
	],
};

//prettier-ignore
export const correctAnswers = { A: ['c',  'b' , 'c' , 'b' , 'c' , 'c' , 'a' , 'a' , 'b' , 'c',
 'b',  'c' ,'a' ,'a'  ,'b' , 'c' , 'c' , 'a' ,'b', 'a',
 'c',  'c' , 'a' ,'c',  'a' , 'b',  'c'  ,'c' , 'c', 'a',
 'b' , 'b' , 'c',  'a' , 'c', 'b' , 'b' , 'c' , 'c' , 'a',
 'c' , 'c' , 'a' , 'c', 'c' , 'a' , 'c'  ,'c'  ,'b' , 'c'], B: [ 'a', 'd' , 'b'  ,'c',  'c' , 'a' , 'd' , 'c'  ,'a' , 'd',
  'c' , 'a' , 'b' , 'b' , 'a' , 'd' , 'c'  ,'c' , 'b' , 'c',
  'c',  'c' , 'a' , 'c' , 'c' , 'd',  'a' , 'd' , 'b' , 'c',
  'd',  'c'  ,'a' , 'b' , 'a' , 'c' , 'b'  ,'c' , 'b' , 'd',
  'a',  'd' , 'd' , 'b' , 'a' , 'd' , 'c' , 'd' , 'a' , 'b'] };

export const answersEvaluation = {
	BelowElementary: [0, 20],
	Elementary: [21, 35],
	PreIntermediate: [36, 60],
	Intermediate: [61, 85],
	UpperIntermediate: [86, 100],
};

export const EMAIL = 'testEmail@gmail.com';
